import { Toaster } from "react-hot-toast";
import "./globals.css";
import Navbar from "@/components/Navbar";
import NextAuthProvider from "@/providers/NextAuthProvider";

export const metadata = {
  title: "Car Doctor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`max-w-[1200px] mx-auto antialiased`}>
        <NextAuthProvider>
          <Navbar />
          <Toaster />
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
